export const data = [
  {
    id: `1`,
    href: `movie-page.html`,
    name: `Fantastic Beasts: The Crimes of Grindelwald`,
    img: `img/fantastic-beasts-the-crimes-of-grindelwald.jpg`,
    alt: `Fantastic Beasts: The Crimes of Grindelwald`,
  },
  {
    id: `2`,
    href: `movie-page.html`,
    name: `Bohemian Rhapsody`,
    img: `img/bohemian-rhapsody.jpg`,
    alt: `Bohemian Rhapsody`,
  },
  {
    id: `3`,
    href: `movie-page.html`,
    name: `Macbeth`,
    img: `img/macbeth.jpg`,
    alt: `Macbeth`,
  },
  {
    id: `4`,
    href: `movie-page.html`,
    name: `Aviator`,
    img: `img/aviator.jpg`,
    alt: `Aviator`,
  },
  {
    id: `5`,
    href: `movie-page.html`,
    name: `We need to talk about Kevin`,
    img: `img/we-need-to-talk-about-kevin.jpg`,
    alt: `We need to talk about Kevin`,
  },
  {
    id: `6`,
    href: `movie-page.html`,
    name: `What We Do in the Shadows`,
    img: `img/what-we-do-in-the-shadows.jpg`,
    alt: `What We Do in the Shadows`,
  },
  {
    id: `7`,
    href: `movie-page.html`,
    name: `Revenant`,
    img: `img/revenant.jpg`,
    alt: `Revenant`,
  },
  {
    id: `8`,
    href: `movie-page.html`,
    name: `Johnny English`,
    img: `img/johnny-english.jpg`,
    alt: `Johnny English`,
  },
  {
    id: `9`,
    href: `movie-page.html`,
    name: `Shutter Island`,
    img: `img/shutter-island.jpg`,
    alt: `Shutter Island`,
  },
  {
    id: `10`,
    href: `movie-page.html`,
    name: `Pulp Fiction`,
    img: `img/pulp-fiction.jpg`,
    alt: `Pulp Fiction`,
  },
  {
    id: `11`,
    href: `movie-page.html`,
    name: `No Country for Old Men`,
    img: `img/no-country-for-old-men.jpg`,
    alt: `No Country for Old Men`,
  },
  {
    id: `12`,
    href: `movie-page.html`,
    name: `Snatch`,
    img: `img/snatch.jpg`,
    alt: `Snatch`,
  },
  {
    id: `13`,
    href: `movie-page.html`,
    name: `Moonrise Kingdom`,
    img: `img/moonrise-kingdom.jpg`,
    alt: `Moonrise Kingdom`,
  },
  {
    id: `14`,
    href: `movie-page.html`,
    name: `Seven Years in Tibet`,
    img: `img/seven-years-in-tibet.jpg`,
    alt: `Seven Years in Tibet`,
  },
  {
    id: `15`,
    href: `movie-page.html`,
    name: `Midnight Special`,
    img: `img/midnight-special.jpg`,
    alt: `Midnight Special`,
  },
  {
    id: `16`,
    href: `movie-page.html`,
    name: `War of the Worlds`,
    img: `img/war-of-the-worlds.jpg`,
    alt: `War of the Worlds`,
  },
  {
    id: `17`,
    href: `movie-page.html`,
    name: `Dardjeeling Limited`,
    img: `img/dardjeeling-limited.jpg`,
    alt: `Dardjeeling Limited`,
  },
  {
    id: `18`,
    href: `movie-page.html`,
    name: `Orlando`,
    img: `img/orlando.jpg`,
    alt: `Orlando`,
  },
  {
    id: `19`,
    href: `movie-page.html`,
    name: `Mindhunter`,
    img: `img/mindhunter.jpg`,
    alt: `Mindhunter`,
  },
  {
    id: `20`,
    href: `movie-page.html`,
    name: `Midnight Special`,
    img: `img/midnight-special.jpg`,
    alt: `Midnight Special`,
  }
];

